image:
- Ubuntu1604
- Ubuntu1804

platform:
  - x86
  - x64

before_build:
  - curl -fsSL https://github.com/reaper-oss/sws/raw/master/reaper/reaper_plugin.h -o vendor/reaper_plugin.h
  - curl -fsSL https://gist.github.com/cfillion/da355e8278048de08ae065d6fe6031c1/raw/reaper_plugin_functions.h -o vendor/reaper_plugin_functions.h
  - git clone -q --depth 1 https://github.com/justinfrankel/WDL.git vendor/WDL

install:
  - docker run --name arch --rm --privileged -tidv `pwd`:/build -w /build
    -e CURLSO=:libcurl.so.3 archlinux/base
  - docker exec arch
   pacman -Syu --noconfirm boost catch2 gcc git libcurl-compat php tup wget

  - if [[ "$PLATFORM" == "x86" ]]; then
      docker exec arch sh -c $'
        echo "[multilib]\nInclude = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf' &&
      docker exec arch
        pacman -Sy --noconfirm lib32-libcurl-compat lib32-gcc-libs lib32-sqlite;
    fi
# HACK: tup needs a parent process to do setpgid successfully
build_script: docker exec arch sh -c "echo tup $PLATFORM | sh"
before_test:      
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install libstdc++6 -qq

  - if [[ "$PLATFORM" == "x86" ]]; then
      sudo apt-get install libcurl3:i386 -qq;
    fi
test_script: '$PLATFORM/bin/test'
artifacts:
  - path: $(PLATFORM)/bin/reaper_reapack*.so
  - path: $(PLATFORM)/bin/test 
